<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>

---

## Домашнее задание: библиотека Numpy и линейная алгебра. Решение


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [26]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.35647625 0.05768853 0.9345776  ... 0.47690418 0.33930844 0.49188407]
 [0.43079235 0.92164308 0.55268182 ... 0.83546575 0.58452968 0.7667884 ]
 [0.614432   0.96339595 0.9112368  ... 0.47200832 0.05550012 0.67192136]
 ...
 [0.32963412 0.90587828 0.54003204 ... 0.45177209 0.522244   0.60640839]
 [0.59802061 0.66814703 0.75734964 ... 0.30602894 0.22509135 0.05359704]
 [0.16826252 0.18758348 0.6076556  ... 0.92348706 0.08682927 0.37272463]]
[[0.79412462 0.04067908 0.54197233 ... 0.61716349 0.88628431 0.1339721 ]
 [0.52603322 0.5057804  0.39643232 ... 0.34684506 0.53099573 0.23973301]
 [0.74801309 0.83711791 0.47492016 ... 0.81949323 0.42452973 0.56156448]
 ...
 [0.51304084 0.20321123 0.69379728 ... 0.32018995 0.4634417  0.93210825]
 [0.12644104 0.72042072 0.03528579 ... 0.71609861 0.78357151 0.28718411]
 [0.43610064 0.53547608 0.22742268 ... 0.08630132 0.30201838 0.76482457]]


In [21]:
def mult(a, b):
    # здесь напишите перемножение матриц без 
    # использования NumPy и выведите результат
#     a = a.tolist() if isinstance(a, np.ndarray) else a 
#     b = b.tolist() if isinstance(b, np.ndarray) else b 
    
    _, m1 = len(a), len(a[0])
    n2, _ = len(b), len(b[0])
    if m1 == n2:  
        return [[sum([r[i] * c[i] for i in range(len(r))]) for c in zip(*b)] for r in a]
        
        
a = np.array([
    [5, 1, -2, 0],
    [0, 3, 4, 3],
    [2, 3, 1, 1]
])

b = np.array([
    [1, -3],
    [2, -2],
    [3, -1],
    [0, 0]
])
print(a.shape, b.shape)
sum([sum(r) for r in mult(a, b)])

(3, 4) (4, 2)


-8

In [23]:
def np_mult(a, b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат
    return a.dot(b)

a = np.array([
    [5, 1, -2, 0],
    [0, 3, 4, 3],
    [2, 3, 1, 1]
])

b = np.array([
    [1, -3],
    [2, -2],
    [3, -1],
    [0, 0]
])

np_mult(a, b).sum()

-8

In [29]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 576 ms, sys: 3.54 ms, total: 580 ms
Wall time: 582 ms


In [32]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 483 µs, sys: 103 µs, total: 586 µs
Wall time: 337 µs


In [33]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.553601691739459e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [34]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.56776034 0.93062938 0.83029833] [0.78787194 0.94919275 0.52574497]


In [64]:
def scalar_product(a,b):
    return sum([a[i] * b[i] for i in range(len(a))])

In [65]:
def np_scalar_product(a,b):
    return a.dot(b)

In [66]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 19 µs, sys: 0 ns, total: 19 µs
Wall time: 21.9 µs
CPU times: user 27 µs, sys: 6 µs, total: 33 µs
Wall time: 37.9 µs
1.7671942743722469 1.7671942743722469


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [110]:
# функция, решающая задачу с помощью NumPy
def diag_2k(a):
    diag = np.diag(a)
    return diag[np.logical_not((diag % 2).astype(bool))].sum()

In [111]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[7, 2, 5, 8, 8],
       [8, 7, 2, 1, 7],
       [2, 3, 2, 3, 2],
       [7, 8, 7, 1, 7],
       [8, 9, 6, 1, 7]])

In [112]:
%%time
# засечем время работы функции с NumPy
diag_2k(a)

CPU times: user 131 µs, sys: 152 µs, total: 283 µs
Wall time: 1.19 ms


2

### Задание 4
Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  

In [113]:
import numpy as np

def cumsum(A):
    return np.cumsum(A, axis=1)

A = np.array([
    [1, 2, 3],
    [1, 3, 5],
    [3, 6, 8]
])

cumsum(A)

array([[ 1,  3,  6],
       [ 1,  4,  9],
       [ 3,  9, 17]])

In [0]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(A):
    return #YOUR CODE

In [0]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3) 

%time S2 = np_sec_av(A)

CPU times: user 616 µs, sys: 0 ns, total: 616 µs
Wall time: 507 µs


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив xс преобразованным xи вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [134]:
# функция, решающая задачу с помощью NumPy
from copy import copy
    
def transform(X, a=1):
    if X.ndim == 1:
        X = X[:, None]
    X_cp = np.copy(X)
    X_cp[:, 1::2] = a
    X_cp[:, ::2] **= 3
    return np.hstack((X, X_cp[:, ::-1]))

X = np.array([[100, 200, 300, 400, 500]])
np_transformation(X)

array([[    100,     200,     300,     400,     500,       1,     400,
              1, 8000000,       1]])

In [136]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy 
%time S2 = transform(X, 5)

CPU times: user 727 µs, sys: 1.81 ms, total: 2.53 ms
Wall time: 2.26 ms


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [166]:
# функция, решающая задачу с помощью NumPy
from itertools import groupby


def encode(a):
    counts, values = [], []
    prev = None  
    i = 0 
    for v in a:
        if prev != v: 
            counts.append(i), values.append(v)
            i = 0
        prev = v
        i += 1 
    counts.append(i)
    
    return np.array(values), np.array(counts[1:]) 


def encode(a):
    values, counts = zip(*[(k, len(list(g))) for k, g in groupby(a)])
    return np.array(values), np.array(counts)

In [167]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

# %time x, num = encode(X)
%time encode(X)

CPU times: user 37 µs, sys: 0 ns, total: 37 µs
Wall time: 41 µs


(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))